Add a check to make sure configuration change happend

diff --git a/bin/multihubctl b/bin/multihubctl
--- a/bin/multihubctl
+++ b/bin/multihubctl
@@ -88,6 +88,21 @@ c.GoogleOAuthenticator.oauth_callback_url = 'https://$urlbase${withslash}/hub/oa
 EOF2
 
 EOF
+
+    # At least once, the above failed for some reason.  Add a check to
+    # make it clear if this happens again.
+    
+    checklastline="$(
+      "$hubdir"/jhvmdir-hub/ssh-to-kvm.sh \
+           sudo docker exec -i root_jupyterhub_1 \
+               tail -n 1 /srv/jupyterhub_config/jupyterhub_config.py
+    )"
+    if [[ "$checklastline" != */$urlbase${withslash}/* ]]; then
+	echo "Attempt to reconfigure a JupyterHub instance failed for some reason." 1>&2
+	echo "Please try running the command again." 1>&2
+	rm -f "$hubdir/hubid"
+	exit 1
+    fi
 }
 
 reconfigure_nginx()
